# Permalinks
permalink:           pretty

# Setup
title:               Russell W. Myers
tagline:             Data Science Blog
url:                 https://rwmyers46/github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Russell W. Myers
  url:               ""
  email:            rwmyers46@

# Custom vars
version:             2.0.0
github:
  repo:              https://rwmyers46/github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

theme: jekyll-theme-slate
